### PR TITLE
✨ Single End Support

### PR DESCRIPTION
**Pull request by dmiller15**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Resolves https://github.com/d3b-center/bixu-tracker/issues/623
Also contains estimates for https://github.com/d3b-center/bixu-tracker/issues/627

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

- [x] Tool passes cwltool validation
- [x] Rabix CLI Validation fails for unknown reasons but it does load fine in Rabix Composer
- [x] SE Fastq W/O Adapter Trimming: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/883ccfdc-3978-48c8-aff8-176c5355f05f/
- [x] SE Fastq With Adapter Trimming: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/7838924a-38f5-4b57-870f-0d35ea6e13ac/
- [x] PE Fastq W/O Adapter Trimming: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/48327762-7f91-459b-9ce8-37c996c240ac/
- [x] PE Fastq With Adapter Trimming: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/dab87069-9bbe-49e9-bda2-b28181afe069/
- [x] SE BAM W/O Adapter Trimming: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/19125e5b-955c-498e-85a0-37c5755fcdac/
- [x] SE BAM With Adapter Trimming: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/b29d5248-42dc-4b93-9185-154961e6609e/
- [x] PE BAM W/O Adapter Trimming: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/f401320f-877f-4cc1-ae76-f196e7521203/
- [x] PE BAM With Adapter Trimming: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/f8f6168d-5d96-4427-9bf3-5e9f48bcb0bb/

**Test Configuration**:
* Environment: Rabix 1.0.5, cwltool 3.0.20200324120055
* Test files: See Cavatica tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by migbro** [comment]
Are there plans to update documentation (both README and cavatica doc) in another PR? This will need to be completed before updating the cavatica public and cutting a new release update

**Comment by dmiller15** [comment]
I'll update the README and doc today and put it in this PR. Shouldn't be much to add as the changes are relatively small from a user's perspective.

**Comment by bmennis** [comment]
Ok so I tested the SE samples I have used in the PBTA Splicing Analysis project. All three tasks completed successfully here:
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/#q?search=RNA&page=1

For comparison to the analysis for the PBTA Splicing project, the completed tasks can be found here:
https://cavatica.sbgenomics.com/u/d3b-bixu/rs-h7xa9jez-pbta-splicing/tasks/#q?search=RNA-Seq-single&page=1&status=COMPLETED

I have taken a quick look at the RNASeQC metrics and they appear to match up. Let me know thoughts on this or if more testing is needed

**Comment by migbro** [comment]
@bmennis , when you have a chance, can you quickly re-run those test samples with this updated wf? Thanks!

**Comment by bmennis** [comment]
Thanks so much for looking at the workflow and making the changes, I will get those re tests running.

**Comment by tkoganti** [comment]
All the runs that @bmennis ran were single end samples. Would it be useful to run a task on paired end as well to make sure that runs as expected?

**Comment by dmiller15** [comment]
From a regression testing point of view, that would be prudent.

**Comment by tkoganti** [comment]
Dan made some updates on cutadapt. Maybe running some tests on paired with adapters and without adapters to make sure everything works might be good

**Comment by migbro** [comment]
Hi @bmennis , when you get a chance, can you run the following tests to close this out, as @tkoganti suggested:
- [ ] SE, bam in
- [ ] SE, bam in, with adapters (odd, but could have an unaligned bam)
- [ ] SE, fastq in
- [ ] SE, fastq in , with adapters
- [ ] PE, bam in
- [ ] PE, bam in, with adapters (odd, but could have an unaligned bam)
- [ ] PE, fastq in
- [ ] PE, fastq in , with adapters

Even if the source doesn't really have adapters, really just to make sure cutadapt runs properly given the input, so you can just use standard illumina to test. Thanks!

**Comment by bmennis** [comment]
I have the SE test samples running here:
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/#q?search=SE-SRR7268791&page=1

I also have the PE samples running here:
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/#q?page=1&search=PE-BS_4X8PQ5G6

**Pull request merged**
